set nu
syntax on
set ruler
set encoding=utf-8
set autoindent
set tabstop=4
set softtabstop=4
set shiftwidth=4
set backspace=2
set smarttab
set history=1000
set nobackup
set ignorecase
set nohlsearch
set incsearch
set formatoptions=tcrqn
set showmatch
set matchtime=5
filetype on
filetype indent on
inoremap ( ()<Esc>i
inoremap [ []<Esc>i
inoremap { {}<Esc>i
inoremap < <><Esc>i
inoremap ` ``<Esc>i
inoremap ' ''<Esc>i
inoremap " ""<Esc>i

set background=dark
" plugin
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'altercation/vim-colors-solarized'
Plugin 'aperezdc/vim-template'
Plugin 'boydos/emmet-vim'

call vundle#end()
filetype plugin indent on
iab xtime <c-r>=strftime("%Y-%m-%d %H:%M:%S %A")<cr>

