FROM centos:7
COPY ./software/downloadFile.tar.gz ./software/vim-plugs.tar.gz ./software/apache-maven-3.6.3-bin.zip ./software/CentOS-AltArch-7.repo ./software/.vimrc /root/Downloads/
RUN mv /root/Downloads/CentOS-AltArch-7.repo /etc/yum.repos.d/CentOS-Base.repo \
	&& yum clean all \
	&& yum makecache \
	&& yum install -y iproute2 git vim binutils curl wget tree bash-completion zip unzip gzip bzip2 java-1.8.0-openjdk java-1.8.0-openjdk-devel \
	&& yum remove -y vim-minimal \
	&& yum clean all \
	&& git config --global color.status auto \
	&& git config --global color.diff auto \
	&& git config --global credential.helper store \
	&& ln -s /usr/bin/vim /usr/bin/vi 

WORKDIR /root/Downloads
RUN tar -xf downloadFile.tar.gz \
	&& bash downloadFile/init.sh /usr/local \
	&& tar -xf ./vim-plugs.tar.gz -C /root \
	&& mv .vimrc /root \
	&& unzip apache-maven-3.6.3-bin.zip -d /opt \
	&& rm -rf /root/Downloads \
	&& echo "JAVA_HOME=$(dirname $(dirname $(readlink -f /usr/bin/javah)))" >> /etc/profile 

ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
ENV M2_HOME /opt/apache-maven-3.6.3/
ENV MAVEN_HOME $M2_HOME
ENV PATH $M2_HOME/bin:$PATH
