FROM centos:7
ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
ENV TZ=Asia/Shanghai
COPY ./conf/.vimrc /root/.vimrc
COPY ./conf/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo
RUN yum clean all \
	&& yum makecache \
	&& yum install -y iproute2 vim binutils curl wget tree bash-completion zip unzip gzip bzip2 \
	&& yum remove -y vim-minimal \
	&& yum clean all \
	&& ln -s /usr/bin/vim /usr/bin/vi 

WORKDIR /webapp
