FROM ubuntu:18.04
COPY ./sources.list /etc/apt/sources.list
COPY ./.vimrc /root/
ADD ./vim-plugs.tar.gz /root/
RUN apt-get update && apt-get install -y apt-utils locales iproute2 git vim binutils curl wget tree && locale-gen en_US.UTF-8 && apt-get clean
ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
EXPOSE 80
