FROM centos:7
COPY ./software/downloadFile.tar.gz ./software/vim-plugs.tar.gz ./software/CentOS-AltArch-7.repo ./software/.vimrc /root/Downloads/
RUN mv /root/Downloads/CentOS-AltArch-7.repo /etc/yum.repos.d/CentOS-Base.repo \
	&& yum clean all \
	&& yum makecache \
	&& yum install -y iproute2 vim binutils curl wget tree bash-completion zip unzip gzip bzip2 \
	&& yum remove -y vim-minimal \
	&& yum clean all \
	&& ln -s /usr/bin/vim /usr/bin/vi 

WORKDIR /root/Downloads
RUN tar -xf downloadFile.tar.gz \
	&& bash downloadFile/init.sh /usr/local \
	&& tar -xf ./vim-plugs.tar.gz -C /root \
	&& mv .vimrc /root \
	&& rm -rf /root/Downloads 

ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
