# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/.local/bin:$HOME/bin:/$HOME/SoftWare/node/bin

export PATH
export linux=/home/wmsj100/Documents/git/LiXin/Linux
export network=/home/wmsj100/Documents/git/LiXin/NetWork
export vmware=/home/wmsj100/Documents/git/LiYang/VMware/Notes
export windows=/home/wmsj100/Documents/git/LiYang/Windows/Notes
