FROM ubuntu:18.04
ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV TZ=Asia/Shanghai 
ENV LD_LIBRARY_PATH=/opt/instantclient_12_2

COPY ./docker/sources.list /etc/apt/sources.list
COPY ./docker/instantclient-basiclite-linux.x64-12.2.0.1.0.zip /tmp/instantclient-basiclite-linux.x64-12.2.0.1.0.zip
COPY ./docker/pip.conf /root/.pip/pip.conf
COPY ./docker/vimrc /root/.vimrc
COPY ./Pipfile* /webapp/

RUN apt update -y \
	&& apt install -y unzip libaio1 python3-dev python3-pip python3-wheel gcc npm \
	&& npm config set registry https://registry.npm.taobao.org \
	&& unzip /tmp/instantclient-basiclite-linux.x64-12.2.0.1.0.zip -d /opt \
	&& rm -f /tmp/instantclient-basiclite-linux.x64-12.2.0.1.0.zip \
	&& apt clean all

WORKDIR /webapp

RUN python3 -m pip install -U pip \
	&& pip3 install pipenv \
	&& pipenv install --deploy --ignore-pipfile \
	&& mkdir log \
	&& touch log/app.log

COPY . /webapp

RUN npm install \
	&& npm cache clean --force \
	&& apt remove -y gcc npm \
	&& mkdir -p static/lib \
	&& cp -a node_modules/bootstrap/dist static/lib/bootstrap \
	&& cp -a node_modules/jquery/dist static/lib/jquery \
	&& cp -a node_modules/popper.js/dist/ static/lib/popper \
	&& rm -rf ./docker node_modules ~/.npm

CMD ["pipenv", "run", "uwsgi", "--ini", "uwsgi.ini"]
