#!/bin/bash
# 脚本需要通过yum下载软件，所以先自行yum update来更新本地数据库，否则脚本会执行较长时间
# 当前脚本会依赖ssh/scp expect
# 执行需要传递文件下载地址，例如http://prdownloads.sourceforge.net/findbugs/findbugs-3.0.1.tar.gz
# 文件在香港主机下载到/tmp目录
# 文件会存放到当前主机的/tmp目录
# 等文件传输完成后清除香港主机的文件
# Author: wanghao 0000206327

TargetHost=root@159.138.0.217
PASSWD=CloudBU@123

if [ $# -lt 1 ];then
	echo "Please input file url"
	exit 1
fi

which scp &>/dev/null
if [ $? -ne 0 ];then
	yum install -y openssh-clients 
fi

which expect &>/dev/null
if [ $? -ne 0 ];then
	yum install -y expect 
fi


URL=$1
File=$(basename $URL)

echo "start to download $File"
expect <<EOF
	set timeout 3000
	spawn ssh $TargetHost wget $URL -O /tmp/$File 
	expect {
		"yes/no" { send "yes\n";exp_continue }
		"password" { send "$PASSWD\n" }
	}
	expect eof
EOF

echo "start cp $File from $TargetHost to /tmp/$File"
expect <<EOF
	set timeout 3000
	spawn scp $TargetHost:/tmp/$File /tmp/
	expect {
		"yes/no" { send "yes\n";exp_continue }
		"password" { send "$PASSWD\n" }
	}
	expect eof
EOF

echo "start clean $TargetHost /tmp/$File"
expect <<EOF
	set timeout 3000
	spawn ssh $TargetHost rm -f /tmp/$File 
	expect {
		"yes/no" { send "yes\n";exp_continue }
		"password" { send "$PASSWD\n" }
	}
	expect eof
EOF
#expect <<EOF
#	set timeout 30
#	spawn ssh $TargetHost
#	expect {
#		"yes/no" { send "yes\n";exp_continue }
#		"password" { send "$PASSWD\n" }
#	}
#	expect "]#" { send "wget $URL -O /tmp/$File\n" }
#	expect "]#" { send ":/tmp/$File /tmp\n" }
#	expect "]#" { send "rm /tmp/$File\n" }
#	expect "]#" { send "exit\n" } expect eof
#EOF
echo "/tmp/$File download complete!!!"
