set nu
syntax on
set ruler
set encoding=utf-8
set autoindent
set tabstop=4
set softtabstop=4
set shiftwidth=4
set backspace=2
set smarttab
set history=1000
set nobackup
set ignorecase
set nohlsearch
set incsearch
set formatoptions=tcrqn
set showmatch
set matchtime=5
filetype on
filetype plugin on
filetype indent on
inoremap ( ()<Esc>i
inoremap [ []<Esc>i
inoremap { {<CR>}<Esc>O
inoremap ' ''<Esc>i
inoremap " ""<Esc>i
set cursorline
hi CursorLine   cterm=NONE ctermbg=darkred ctermfg=white guibg=darkred guifg=white
